language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 7.0
      env:
        - DEPENDENCIES=lowest

install:
  - composer install --no-interaction
  - if [ "$DEPENDENCIES" = "lowest" ]; then composer update --prefer-lowest -n; fi
  
script:
  - ./vendor/bin/phpunit --coverage-text
